# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Cindy Chong/Desktop/EE361/Lab4.1A/Lab4.1A.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Cindy Chong/Desktop/EE361/Lab4.1A/Lab4.1A.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Cindy Chong/Desktop/EE361/Lab4.1A/Lab4.1A.srcs/sources_1/new/test.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Cindy Chong/Desktop/EE361/Lab4.1A/Lab4.1A.srcs/constrs_1/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Cindy Chong/Desktop/EE361/Lab4.1A/Lab4.1A.srcs/constrs_1/new/Basys3_Master.xdc}}]


synth_design -top test -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test.dcp

catch { report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb }
